/**
 * This class is generated by jOOQ
 */
package com.example.model.tables.records;


import com.example.model.tables.Note;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteRecord extends UpdatableRecordImpl<NoteRecord> implements Record15<Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Object, Object> {

	private static final long serialVersionUID = 601425482;

	/**
	 * Setter for <code>public.note.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.note.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.note.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.note.site_id</code>.
	 */
	public Integer getSiteId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.note.notetype_id</code>.
	 */
	public void setNotetypeId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.note.notetype_id</code>.
	 */
	public Integer getNotetypeId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.note.property_id</code>.
	 */
	public void setPropertyId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.note.property_id</code>.
	 */
	public Integer getPropertyId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.note.sitevisit_id</code>.
	 */
	public void setSitevisitId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.note.sitevisit_id</code>.
	 */
	public Integer getSitevisitId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.note.notedate</code>.
	 */
	public void setNotedate(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.note.notedate</code>.
	 */
	public Timestamp getNotedate() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.note.secondarydate</code>.
	 */
	public void setSecondarydate(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.note.secondarydate</code>.
	 */
	public Timestamp getSecondarydate() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.note.note</code>.
	 */
	public void setNote(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.note.note</code>.
	 */
	public String getNote() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.note.createddate</code>.
	 */
	public void setCreateddate(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.note.createddate</code>.
	 */
	public Timestamp getCreateddate() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>public.note.createdby</code>.
	 */
	public void setCreatedby(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.note.createdby</code>.
	 */
	public Integer getCreatedby() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>public.note.lastmodifieddate</code>.
	 */
	public void setLastmodifieddate(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.note.lastmodifieddate</code>.
	 */
	public Timestamp getLastmodifieddate() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>public.note.secondarydatechangedby_id</code>.
	 */
	public void setSecondarydatechangedbyId(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.note.secondarydatechangedby_id</code>.
	 */
	public Integer getSecondarydatechangedbyId() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>public.note.secondarydatechangedate</code>.
	 */
	public void setSecondarydatechangedate(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.note.secondarydatechangedate</code>.
	 */
	public Timestamp getSecondarydatechangedate() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>public.note.dealissues</code>.
	 */
	public void setDealissues(Object value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.note.dealissues</code>.
	 */
	public Object getDealissues() {
		return (Object) getValue(13);
	}

	/**
	 * Setter for <code>public.note.discussionpoints</code>.
	 */
	public void setDiscussionpoints(Object value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.note.discussionpoints</code>.
	 */
	public Object getDiscussionpoints() {
		return (Object) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Object, Object> fieldsRow() {
		return (Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Object, Object> valuesRow() {
		return (Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Note.NOTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Note.NOTE.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Note.NOTE.NOTETYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Note.NOTE.PROPERTY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Note.NOTE.SITEVISIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Note.NOTE.NOTEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Note.NOTE.SECONDARYDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Note.NOTE.NOTE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Note.NOTE.CREATEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Note.NOTE.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return Note.NOTE.LASTMODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Note.NOTE.SECONDARYDATECHANGEDBY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return Note.NOTE.SECONDARYDATECHANGEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field14() {
		return Note.NOTE.DEALISSUES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field15() {
		return Note.NOTE.DISCUSSIONPOINTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNotetypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPropertyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getSitevisitId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getNotedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getSecondarydate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreateddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getLastmodifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getSecondarydatechangedbyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getSecondarydatechangedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value14() {
		return getDealissues();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value15() {
		return getDiscussionpoints();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value2(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value3(Integer value) {
		setNotetypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value4(Integer value) {
		setPropertyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value5(Integer value) {
		setSitevisitId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value6(Timestamp value) {
		setNotedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value7(Timestamp value) {
		setSecondarydate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value8(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value9(Timestamp value) {
		setCreateddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value10(Integer value) {
		setCreatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value11(Timestamp value) {
		setLastmodifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value12(Integer value) {
		setSecondarydatechangedbyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value13(Timestamp value) {
		setSecondarydatechangedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value14(Object value) {
		setDealissues(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord value15(Object value) {
		setDiscussionpoints(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NoteRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7, String value8, Timestamp value9, Integer value10, Timestamp value11, Integer value12, Timestamp value13, Object value14, Object value15) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NoteRecord
	 */
	public NoteRecord() {
		super(Note.NOTE);
	}

	/**
	 * Create a detached, initialised NoteRecord
	 */
	public NoteRecord(Integer id, Integer siteId, Integer notetypeId, Integer propertyId, Integer sitevisitId, Timestamp notedate, Timestamp secondarydate, String note, Timestamp createddate, Integer createdby, Timestamp lastmodifieddate, Integer secondarydatechangedbyId, Timestamp secondarydatechangedate, Object dealissues, Object discussionpoints) {
		super(Note.NOTE);

		setValue(0, id);
		setValue(1, siteId);
		setValue(2, notetypeId);
		setValue(3, propertyId);
		setValue(4, sitevisitId);
		setValue(5, notedate);
		setValue(6, secondarydate);
		setValue(7, note);
		setValue(8, createddate);
		setValue(9, createdby);
		setValue(10, lastmodifieddate);
		setValue(11, secondarydatechangedbyId);
		setValue(12, secondarydatechangedate);
		setValue(13, dealissues);
		setValue(14, discussionpoints);
	}
}
