/**
 * This class is generated by jOOQ
 */
package com.example.model.tables.records;


import com.example.model.tables.Svals;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SvalsRecord extends TableRecordImpl<SvalsRecord> {

	private static final long serialVersionUID = -1787420516;

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SvalsRecord
	 */
	public SvalsRecord() {
		super(Svals.SVALS);
	}
}
