/**
 * This class is generated by jOOQ
 */
package com.example.model.tables.records;


import com.example.model.tables.Tenant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TenantRecord extends UpdatableRecordImpl<TenantRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -1921736146;

	/**
	 * Setter for <code>public.tenant.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.tenant.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.tenant.public_key</code>.
	 */
	public void setPublicKey(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.tenant.public_key</code>.
	 */
	public String getPublicKey() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tenant.TENANT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Tenant.TENANT.PUBLIC_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPublicKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TenantRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TenantRecord value2(String value) {
		setPublicKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TenantRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TenantRecord
	 */
	public TenantRecord() {
		super(Tenant.TENANT);
	}

	/**
	 * Create a detached, initialised TenantRecord
	 */
	public TenantRecord(Integer id, String publicKey) {
		super(Tenant.TENANT);

		setValue(0, id);
		setValue(1, publicKey);
	}
}
