/**
 * This class is generated by jOOQ
 */
package com.example.model;


import com.example.model.tables.Note;
import com.example.model.tables.Notetype;
import com.example.model.tables.Site;
import com.example.model.tables.records.NoteRecord;
import com.example.model.tables.records.NotetypeRecord;
import com.example.model.tables.records.SiteRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<NoteRecord> NOTE_PKEY = UniqueKeys0.NOTE_PKEY;
	public static final UniqueKey<NotetypeRecord> NOTETYPE_PKEY = UniqueKeys0.NOTETYPE_PKEY;
	public static final UniqueKey<SiteRecord> SITE_PKEY = UniqueKeys0.SITE_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<NoteRecord, SiteRecord> NOTE__NOTE_SITE_ID_FKEY = ForeignKeys0.NOTE__NOTE_SITE_ID_FKEY;
	public static final ForeignKey<NoteRecord, NotetypeRecord> NOTE__NOTE_NOTETYPE_ID_FKEY = ForeignKeys0.NOTE__NOTE_NOTETYPE_ID_FKEY;
	public static final ForeignKey<NotetypeRecord, SiteRecord> NOTETYPE__NOTETYPE_SITE_ID_FKEY = ForeignKeys0.NOTETYPE__NOTETYPE_SITE_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<NoteRecord> NOTE_PKEY = createUniqueKey(Note.NOTE, Note.NOTE.ID);
		public static final UniqueKey<NotetypeRecord> NOTETYPE_PKEY = createUniqueKey(Notetype.NOTETYPE, Notetype.NOTETYPE.ID);
		public static final UniqueKey<SiteRecord> SITE_PKEY = createUniqueKey(Site.SITE, Site.SITE.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<NoteRecord, SiteRecord> NOTE__NOTE_SITE_ID_FKEY = createForeignKey(com.example.model.Keys.SITE_PKEY, Note.NOTE, Note.NOTE.SITE_ID);
		public static final ForeignKey<NoteRecord, NotetypeRecord> NOTE__NOTE_NOTETYPE_ID_FKEY = createForeignKey(com.example.model.Keys.NOTETYPE_PKEY, Note.NOTE, Note.NOTE.NOTETYPE_ID);
		public static final ForeignKey<NotetypeRecord, SiteRecord> NOTETYPE__NOTETYPE_SITE_ID_FKEY = createForeignKey(com.example.model.Keys.SITE_PKEY, Notetype.NOTETYPE, Notetype.NOTETYPE.SITE_ID);
	}
}
