/**
 * This class is generated by jOOQ
 */
package com.example.model;


import com.example.model.routines.Akeys;
import com.example.model.routines.Avals;
import com.example.model.routines.Defined;
import com.example.model.routines.Delete1;
import com.example.model.routines.Delete2;
import com.example.model.routines.Delete3;
import com.example.model.routines.Exist;
import com.example.model.routines.ExistsAll;
import com.example.model.routines.ExistsAny;
import com.example.model.routines.Fetchval;
import com.example.model.routines.GhstoreCompress;
import com.example.model.routines.GhstoreConsistent;
import com.example.model.routines.GhstoreDecompress;
import com.example.model.routines.GhstoreIn;
import com.example.model.routines.GhstoreOut;
import com.example.model.routines.GhstorePenalty;
import com.example.model.routines.GhstorePicksplit;
import com.example.model.routines.GhstoreSame;
import com.example.model.routines.GhstoreUnion;
import com.example.model.routines.GinConsistentHstore;
import com.example.model.routines.GinExtractHstore;
import com.example.model.routines.GinExtractHstoreQuery;
import com.example.model.routines.HsConcat;
import com.example.model.routines.HsContained;
import com.example.model.routines.HsContains;
import com.example.model.routines.Hstore1;
import com.example.model.routines.Hstore2;
import com.example.model.routines.Hstore3;
import com.example.model.routines.Hstore4;
import com.example.model.routines.HstoreCmp;
import com.example.model.routines.HstoreEq;
import com.example.model.routines.HstoreGe;
import com.example.model.routines.HstoreGt;
import com.example.model.routines.HstoreHash;
import com.example.model.routines.HstoreIn;
import com.example.model.routines.HstoreLe;
import com.example.model.routines.HstoreLt;
import com.example.model.routines.HstoreNe;
import com.example.model.routines.HstoreOut;
import com.example.model.routines.HstoreRecv;
import com.example.model.routines.HstoreSend;
import com.example.model.routines.HstoreToArray;
import com.example.model.routines.HstoreToJson;
import com.example.model.routines.HstoreToJsonLoose;
import com.example.model.routines.HstoreToJsonb;
import com.example.model.routines.HstoreToJsonbLoose;
import com.example.model.routines.HstoreToMatrix;
import com.example.model.routines.HstoreVersionDiag;
import com.example.model.routines.Isdefined;
import com.example.model.routines.Isexists;
import com.example.model.routines.PopulateRecord;
import com.example.model.routines.Slice;
import com.example.model.routines.SliceArray;
import com.example.model.routines.Tconvert;
import com.example.model.tables.Each;
import com.example.model.tables.Skeys;
import com.example.model.tables.Svals;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Record;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>public.akeys</code>
	 */
	public static String[] akeys(Configuration configuration, Object __1) {
		Akeys f = new Akeys();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.akeys</code> as a field
	 */
	public static Field<String[]> akeys(Object __1) {
		Akeys f = new Akeys();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.akeys</code> as a field
	 */
	public static Field<String[]> akeys(Field<Object> __1) {
		Akeys f = new Akeys();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.avals</code>
	 */
	public static String[] avals(Configuration configuration, Object __1) {
		Avals f = new Avals();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.avals</code> as a field
	 */
	public static Field<String[]> avals(Object __1) {
		Avals f = new Avals();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.avals</code> as a field
	 */
	public static Field<String[]> avals(Field<Object> __1) {
		Avals f = new Avals();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.defined</code>
	 */
	public static Boolean defined(Configuration configuration, Object __1, String __2) {
		Defined f = new Defined();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.defined</code> as a field
	 */
	public static Field<Boolean> defined(Object __1, String __2) {
		Defined f = new Defined();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.defined</code> as a field
	 */
	public static Field<Boolean> defined(Field<Object> __1, Field<String> __2) {
		Defined f = new Defined();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.delete</code>
	 */
	public static Object delete1(Configuration configuration, Object __1, String __2) {
		Delete1 f = new Delete1();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete1(Object __1, String __2) {
		Delete1 f = new Delete1();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete1(Field<Object> __1, Field<String> __2) {
		Delete1 f = new Delete1();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.delete</code>
	 */
	public static Object delete2(Configuration configuration, Object __1, String[] __2) {
		Delete2 f = new Delete2();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete2(Object __1, String[] __2) {
		Delete2 f = new Delete2();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete2(Field<Object> __1, Field<String[]> __2) {
		Delete2 f = new Delete2();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.delete</code>
	 */
	public static Object delete3(Configuration configuration, Object __1, Object __2) {
		Delete3 f = new Delete3();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete3(Object __1, Object __2) {
		Delete3 f = new Delete3();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.delete</code> as a field
	 */
	public static Field<Object> delete3(Field<Object> __1, Field<Object> __2) {
		Delete3 f = new Delete3();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.exist</code>
	 */
	public static Boolean exist(Configuration configuration, Object __1, String __2) {
		Exist f = new Exist();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.exist</code> as a field
	 */
	public static Field<Boolean> exist(Object __1, String __2) {
		Exist f = new Exist();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.exist</code> as a field
	 */
	public static Field<Boolean> exist(Field<Object> __1, Field<String> __2) {
		Exist f = new Exist();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.exists_all</code>
	 */
	public static Boolean existsAll(Configuration configuration, Object __1, String[] __2) {
		ExistsAll f = new ExistsAll();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.exists_all</code> as a field
	 */
	public static Field<Boolean> existsAll(Object __1, String[] __2) {
		ExistsAll f = new ExistsAll();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.exists_all</code> as a field
	 */
	public static Field<Boolean> existsAll(Field<Object> __1, Field<String[]> __2) {
		ExistsAll f = new ExistsAll();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.exists_any</code>
	 */
	public static Boolean existsAny(Configuration configuration, Object __1, String[] __2) {
		ExistsAny f = new ExistsAny();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.exists_any</code> as a field
	 */
	public static Field<Boolean> existsAny(Object __1, String[] __2) {
		ExistsAny f = new ExistsAny();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.exists_any</code> as a field
	 */
	public static Field<Boolean> existsAny(Field<Object> __1, Field<String[]> __2) {
		ExistsAny f = new ExistsAny();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.fetchval</code>
	 */
	public static String fetchval(Configuration configuration, Object __1, String __2) {
		Fetchval f = new Fetchval();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.fetchval</code> as a field
	 */
	public static Field<String> fetchval(Object __1, String __2) {
		Fetchval f = new Fetchval();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.fetchval</code> as a field
	 */
	public static Field<String> fetchval(Field<Object> __1, Field<String> __2) {
		Fetchval f = new Fetchval();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_compress</code>
	 */
	public static Object ghstoreCompress(Configuration configuration, Object __1) {
		GhstoreCompress f = new GhstoreCompress();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_compress</code> as a field
	 */
	public static Field<Object> ghstoreCompress(Object __1) {
		GhstoreCompress f = new GhstoreCompress();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_compress</code> as a field
	 */
	public static Field<Object> ghstoreCompress(Field<Object> __1) {
		GhstoreCompress f = new GhstoreCompress();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_consistent</code>
	 */
	public static Boolean ghstoreConsistent(Configuration configuration, Object __1, Object __2, Integer __3, Long __4, Object __5) {
		GhstoreConsistent f = new GhstoreConsistent();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_consistent</code> as a field
	 */
	public static Field<Boolean> ghstoreConsistent(Object __1, Object __2, Integer __3, Long __4, Object __5) {
		GhstoreConsistent f = new GhstoreConsistent();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_consistent</code> as a field
	 */
	public static Field<Boolean> ghstoreConsistent(Field<Object> __1, Field<Object> __2, Field<Integer> __3, Field<Long> __4, Field<Object> __5) {
		GhstoreConsistent f = new GhstoreConsistent();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_decompress</code>
	 */
	public static Object ghstoreDecompress(Configuration configuration, Object __1) {
		GhstoreDecompress f = new GhstoreDecompress();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_decompress</code> as a field
	 */
	public static Field<Object> ghstoreDecompress(Object __1) {
		GhstoreDecompress f = new GhstoreDecompress();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_decompress</code> as a field
	 */
	public static Field<Object> ghstoreDecompress(Field<Object> __1) {
		GhstoreDecompress f = new GhstoreDecompress();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_in</code>
	 */
	public static Object ghstoreIn(Configuration configuration, Object __1) {
		GhstoreIn f = new GhstoreIn();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_in</code> as a field
	 */
	public static Field<Object> ghstoreIn(Object __1) {
		GhstoreIn f = new GhstoreIn();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_in</code> as a field
	 */
	public static Field<Object> ghstoreIn(Field<Object> __1) {
		GhstoreIn f = new GhstoreIn();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_out</code>
	 */
	public static Object ghstoreOut(Configuration configuration, Object __1) {
		GhstoreOut f = new GhstoreOut();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_out</code> as a field
	 */
	public static Field<Object> ghstoreOut(Object __1) {
		GhstoreOut f = new GhstoreOut();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_out</code> as a field
	 */
	public static Field<Object> ghstoreOut(Field<Object> __1) {
		GhstoreOut f = new GhstoreOut();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_penalty</code>
	 */
	public static Object ghstorePenalty(Configuration configuration, Object __1, Object __2, Object __3) {
		GhstorePenalty f = new GhstorePenalty();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_penalty</code> as a field
	 */
	public static Field<Object> ghstorePenalty(Object __1, Object __2, Object __3) {
		GhstorePenalty f = new GhstorePenalty();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_penalty</code> as a field
	 */
	public static Field<Object> ghstorePenalty(Field<Object> __1, Field<Object> __2, Field<Object> __3) {
		GhstorePenalty f = new GhstorePenalty();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_picksplit</code>
	 */
	public static Object ghstorePicksplit(Configuration configuration, Object __1, Object __2) {
		GhstorePicksplit f = new GhstorePicksplit();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_picksplit</code> as a field
	 */
	public static Field<Object> ghstorePicksplit(Object __1, Object __2) {
		GhstorePicksplit f = new GhstorePicksplit();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_picksplit</code> as a field
	 */
	public static Field<Object> ghstorePicksplit(Field<Object> __1, Field<Object> __2) {
		GhstorePicksplit f = new GhstorePicksplit();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_same</code>
	 */
	public static Object ghstoreSame(Configuration configuration, Object __1, Object __2, Object __3) {
		GhstoreSame f = new GhstoreSame();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_same</code> as a field
	 */
	public static Field<Object> ghstoreSame(Object __1, Object __2, Object __3) {
		GhstoreSame f = new GhstoreSame();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_same</code> as a field
	 */
	public static Field<Object> ghstoreSame(Field<Object> __1, Field<Object> __2, Field<Object> __3) {
		GhstoreSame f = new GhstoreSame();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);

		return f.asField();
	}

	/**
	 * Call <code>public.ghstore_union</code>
	 */
	public static Object ghstoreUnion(Configuration configuration, Object __1, Object __2) {
		GhstoreUnion f = new GhstoreUnion();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.ghstore_union</code> as a field
	 */
	public static Field<Object> ghstoreUnion(Object __1, Object __2) {
		GhstoreUnion f = new GhstoreUnion();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.ghstore_union</code> as a field
	 */
	public static Field<Object> ghstoreUnion(Field<Object> __1, Field<Object> __2) {
		GhstoreUnion f = new GhstoreUnion();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.gin_consistent_hstore</code>
	 */
	public static Boolean ginConsistentHstore(Configuration configuration, Object __1, Short __2, Object __3, Integer __4, Object __5, Object __6) {
		GinConsistentHstore f = new GinConsistentHstore();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);
		f.set__6(__6);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.gin_consistent_hstore</code> as a field
	 */
	public static Field<Boolean> ginConsistentHstore(Object __1, Short __2, Object __3, Integer __4, Object __5, Object __6) {
		GinConsistentHstore f = new GinConsistentHstore();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);
		f.set__6(__6);

		return f.asField();
	}

	/**
	 * Get <code>public.gin_consistent_hstore</code> as a field
	 */
	public static Field<Boolean> ginConsistentHstore(Field<Object> __1, Field<Short> __2, Field<Object> __3, Field<Integer> __4, Field<Object> __5, Field<Object> __6) {
		GinConsistentHstore f = new GinConsistentHstore();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);
		f.set__6(__6);

		return f.asField();
	}

	/**
	 * Call <code>public.gin_extract_hstore</code>
	 */
	public static Object ginExtractHstore(Configuration configuration, Object __1, Object __2) {
		GinExtractHstore f = new GinExtractHstore();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.gin_extract_hstore</code> as a field
	 */
	public static Field<Object> ginExtractHstore(Object __1, Object __2) {
		GinExtractHstore f = new GinExtractHstore();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.gin_extract_hstore</code> as a field
	 */
	public static Field<Object> ginExtractHstore(Field<Object> __1, Field<Object> __2) {
		GinExtractHstore f = new GinExtractHstore();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.gin_extract_hstore_query</code>
	 */
	public static Object ginExtractHstoreQuery(Configuration configuration, Object __1, Object __2, Short __3, Object __4, Object __5) {
		GinExtractHstoreQuery f = new GinExtractHstoreQuery();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.gin_extract_hstore_query</code> as a field
	 */
	public static Field<Object> ginExtractHstoreQuery(Object __1, Object __2, Short __3, Object __4, Object __5) {
		GinExtractHstoreQuery f = new GinExtractHstoreQuery();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		return f.asField();
	}

	/**
	 * Get <code>public.gin_extract_hstore_query</code> as a field
	 */
	public static Field<Object> ginExtractHstoreQuery(Field<Object> __1, Field<Object> __2, Field<Short> __3, Field<Object> __4, Field<Object> __5) {
		GinExtractHstoreQuery f = new GinExtractHstoreQuery();
		f.set__1(__1);
		f.set__2(__2);
		f.set__3(__3);
		f.set__4(__4);
		f.set__5(__5);

		return f.asField();
	}

	/**
	 * Call <code>public.hs_concat</code>
	 */
	public static Object hsConcat(Configuration configuration, Object __1, Object __2) {
		HsConcat f = new HsConcat();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hs_concat</code> as a field
	 */
	public static Field<Object> hsConcat(Object __1, Object __2) {
		HsConcat f = new HsConcat();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hs_concat</code> as a field
	 */
	public static Field<Object> hsConcat(Field<Object> __1, Field<Object> __2) {
		HsConcat f = new HsConcat();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hs_contained</code>
	 */
	public static Boolean hsContained(Configuration configuration, Object __1, Object __2) {
		HsContained f = new HsContained();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hs_contained</code> as a field
	 */
	public static Field<Boolean> hsContained(Object __1, Object __2) {
		HsContained f = new HsContained();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hs_contained</code> as a field
	 */
	public static Field<Boolean> hsContained(Field<Object> __1, Field<Object> __2) {
		HsContained f = new HsContained();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hs_contains</code>
	 */
	public static Boolean hsContains(Configuration configuration, Object __1, Object __2) {
		HsContains f = new HsContains();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hs_contains</code> as a field
	 */
	public static Field<Boolean> hsContains(Object __1, Object __2) {
		HsContains f = new HsContains();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hs_contains</code> as a field
	 */
	public static Field<Boolean> hsContains(Field<Object> __1, Field<Object> __2) {
		HsContains f = new HsContains();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore</code>
	 */
	public static Object hstore1(Configuration configuration, String __1, String __2) {
		Hstore1 f = new Hstore1();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore1(String __1, String __2) {
		Hstore1 f = new Hstore1();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore1(Field<String> __1, Field<String> __2) {
		Hstore1 f = new Hstore1();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore</code>
	 */
	public static Object hstore2(Configuration configuration, String[] __1, String[] __2) {
		Hstore2 f = new Hstore2();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore2(String[] __1, String[] __2) {
		Hstore2 f = new Hstore2();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore2(Field<String[]> __1, Field<String[]> __2) {
		Hstore2 f = new Hstore2();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore</code>
	 */
	public static Object hstore3(Configuration configuration, String[] __1) {
		Hstore3 f = new Hstore3();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore3(String[] __1) {
		Hstore3 f = new Hstore3();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore3(Field<String[]> __1) {
		Hstore3 f = new Hstore3();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore</code>
	 */
	public static Object hstore4(Configuration configuration, Record __1) {
		Hstore4 f = new Hstore4();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore4(Record __1) {
		Hstore4 f = new Hstore4();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore</code> as a field
	 */
	public static Field<Object> hstore4(Field<Record> __1) {
		Hstore4 f = new Hstore4();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_cmp</code>
	 */
	public static Integer hstoreCmp(Configuration configuration, Object __1, Object __2) {
		HstoreCmp f = new HstoreCmp();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_cmp</code> as a field
	 */
	public static Field<Integer> hstoreCmp(Object __1, Object __2) {
		HstoreCmp f = new HstoreCmp();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_cmp</code> as a field
	 */
	public static Field<Integer> hstoreCmp(Field<Object> __1, Field<Object> __2) {
		HstoreCmp f = new HstoreCmp();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_eq</code>
	 */
	public static Boolean hstoreEq(Configuration configuration, Object __1, Object __2) {
		HstoreEq f = new HstoreEq();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_eq</code> as a field
	 */
	public static Field<Boolean> hstoreEq(Object __1, Object __2) {
		HstoreEq f = new HstoreEq();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_eq</code> as a field
	 */
	public static Field<Boolean> hstoreEq(Field<Object> __1, Field<Object> __2) {
		HstoreEq f = new HstoreEq();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_ge</code>
	 */
	public static Boolean hstoreGe(Configuration configuration, Object __1, Object __2) {
		HstoreGe f = new HstoreGe();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_ge</code> as a field
	 */
	public static Field<Boolean> hstoreGe(Object __1, Object __2) {
		HstoreGe f = new HstoreGe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_ge</code> as a field
	 */
	public static Field<Boolean> hstoreGe(Field<Object> __1, Field<Object> __2) {
		HstoreGe f = new HstoreGe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_gt</code>
	 */
	public static Boolean hstoreGt(Configuration configuration, Object __1, Object __2) {
		HstoreGt f = new HstoreGt();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_gt</code> as a field
	 */
	public static Field<Boolean> hstoreGt(Object __1, Object __2) {
		HstoreGt f = new HstoreGt();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_gt</code> as a field
	 */
	public static Field<Boolean> hstoreGt(Field<Object> __1, Field<Object> __2) {
		HstoreGt f = new HstoreGt();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_hash</code>
	 */
	public static Integer hstoreHash(Configuration configuration, Object __1) {
		HstoreHash f = new HstoreHash();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_hash</code> as a field
	 */
	public static Field<Integer> hstoreHash(Object __1) {
		HstoreHash f = new HstoreHash();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_hash</code> as a field
	 */
	public static Field<Integer> hstoreHash(Field<Object> __1) {
		HstoreHash f = new HstoreHash();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_in</code>
	 */
	public static Object hstoreIn(Configuration configuration, Object __1) {
		HstoreIn f = new HstoreIn();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_in</code> as a field
	 */
	public static Field<Object> hstoreIn(Object __1) {
		HstoreIn f = new HstoreIn();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_in</code> as a field
	 */
	public static Field<Object> hstoreIn(Field<Object> __1) {
		HstoreIn f = new HstoreIn();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_le</code>
	 */
	public static Boolean hstoreLe(Configuration configuration, Object __1, Object __2) {
		HstoreLe f = new HstoreLe();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_le</code> as a field
	 */
	public static Field<Boolean> hstoreLe(Object __1, Object __2) {
		HstoreLe f = new HstoreLe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_le</code> as a field
	 */
	public static Field<Boolean> hstoreLe(Field<Object> __1, Field<Object> __2) {
		HstoreLe f = new HstoreLe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_lt</code>
	 */
	public static Boolean hstoreLt(Configuration configuration, Object __1, Object __2) {
		HstoreLt f = new HstoreLt();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_lt</code> as a field
	 */
	public static Field<Boolean> hstoreLt(Object __1, Object __2) {
		HstoreLt f = new HstoreLt();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_lt</code> as a field
	 */
	public static Field<Boolean> hstoreLt(Field<Object> __1, Field<Object> __2) {
		HstoreLt f = new HstoreLt();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_ne</code>
	 */
	public static Boolean hstoreNe(Configuration configuration, Object __1, Object __2) {
		HstoreNe f = new HstoreNe();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_ne</code> as a field
	 */
	public static Field<Boolean> hstoreNe(Object __1, Object __2) {
		HstoreNe f = new HstoreNe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_ne</code> as a field
	 */
	public static Field<Boolean> hstoreNe(Field<Object> __1, Field<Object> __2) {
		HstoreNe f = new HstoreNe();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_out</code>
	 */
	public static Object hstoreOut(Configuration configuration, Object __1) {
		HstoreOut f = new HstoreOut();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_out</code> as a field
	 */
	public static Field<Object> hstoreOut(Object __1) {
		HstoreOut f = new HstoreOut();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_out</code> as a field
	 */
	public static Field<Object> hstoreOut(Field<Object> __1) {
		HstoreOut f = new HstoreOut();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_recv</code>
	 */
	public static Object hstoreRecv(Configuration configuration, Object __1) {
		HstoreRecv f = new HstoreRecv();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_recv</code> as a field
	 */
	public static Field<Object> hstoreRecv(Object __1) {
		HstoreRecv f = new HstoreRecv();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_recv</code> as a field
	 */
	public static Field<Object> hstoreRecv(Field<Object> __1) {
		HstoreRecv f = new HstoreRecv();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_send</code>
	 */
	public static byte[] hstoreSend(Configuration configuration, Object __1) {
		HstoreSend f = new HstoreSend();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_send</code> as a field
	 */
	public static Field<byte[]> hstoreSend(Object __1) {
		HstoreSend f = new HstoreSend();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_send</code> as a field
	 */
	public static Field<byte[]> hstoreSend(Field<Object> __1) {
		HstoreSend f = new HstoreSend();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_array</code>
	 */
	public static String[] hstoreToArray(Configuration configuration, Object __1) {
		HstoreToArray f = new HstoreToArray();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_array</code> as a field
	 */
	public static Field<String[]> hstoreToArray(Object __1) {
		HstoreToArray f = new HstoreToArray();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_array</code> as a field
	 */
	public static Field<String[]> hstoreToArray(Field<Object> __1) {
		HstoreToArray f = new HstoreToArray();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_json</code>
	 */
	public static Object hstoreToJson(Configuration configuration, Object __1) {
		HstoreToJson f = new HstoreToJson();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_json</code> as a field
	 */
	public static Field<Object> hstoreToJson(Object __1) {
		HstoreToJson f = new HstoreToJson();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_json</code> as a field
	 */
	public static Field<Object> hstoreToJson(Field<Object> __1) {
		HstoreToJson f = new HstoreToJson();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_jsonb</code>
	 */
	public static Object hstoreToJsonb(Configuration configuration, Object __1) {
		HstoreToJsonb f = new HstoreToJsonb();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_jsonb</code> as a field
	 */
	public static Field<Object> hstoreToJsonb(Object __1) {
		HstoreToJsonb f = new HstoreToJsonb();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_jsonb</code> as a field
	 */
	public static Field<Object> hstoreToJsonb(Field<Object> __1) {
		HstoreToJsonb f = new HstoreToJsonb();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_jsonb_loose</code>
	 */
	public static Object hstoreToJsonbLoose(Configuration configuration, Object __1) {
		HstoreToJsonbLoose f = new HstoreToJsonbLoose();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_jsonb_loose</code> as a field
	 */
	public static Field<Object> hstoreToJsonbLoose(Object __1) {
		HstoreToJsonbLoose f = new HstoreToJsonbLoose();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_jsonb_loose</code> as a field
	 */
	public static Field<Object> hstoreToJsonbLoose(Field<Object> __1) {
		HstoreToJsonbLoose f = new HstoreToJsonbLoose();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_json_loose</code>
	 */
	public static Object hstoreToJsonLoose(Configuration configuration, Object __1) {
		HstoreToJsonLoose f = new HstoreToJsonLoose();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_json_loose</code> as a field
	 */
	public static Field<Object> hstoreToJsonLoose(Object __1) {
		HstoreToJsonLoose f = new HstoreToJsonLoose();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_json_loose</code> as a field
	 */
	public static Field<Object> hstoreToJsonLoose(Field<Object> __1) {
		HstoreToJsonLoose f = new HstoreToJsonLoose();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_to_matrix</code>
	 */
	public static String[] hstoreToMatrix(Configuration configuration, Object __1) {
		HstoreToMatrix f = new HstoreToMatrix();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_to_matrix</code> as a field
	 */
	public static Field<String[]> hstoreToMatrix(Object __1) {
		HstoreToMatrix f = new HstoreToMatrix();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_to_matrix</code> as a field
	 */
	public static Field<String[]> hstoreToMatrix(Field<Object> __1) {
		HstoreToMatrix f = new HstoreToMatrix();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.hstore_version_diag</code>
	 */
	public static Integer hstoreVersionDiag(Configuration configuration, Object __1) {
		HstoreVersionDiag f = new HstoreVersionDiag();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.hstore_version_diag</code> as a field
	 */
	public static Field<Integer> hstoreVersionDiag(Object __1) {
		HstoreVersionDiag f = new HstoreVersionDiag();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.hstore_version_diag</code> as a field
	 */
	public static Field<Integer> hstoreVersionDiag(Field<Object> __1) {
		HstoreVersionDiag f = new HstoreVersionDiag();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Call <code>public.isdefined</code>
	 */
	public static Boolean isdefined(Configuration configuration, Object __1, String __2) {
		Isdefined f = new Isdefined();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.isdefined</code> as a field
	 */
	public static Field<Boolean> isdefined(Object __1, String __2) {
		Isdefined f = new Isdefined();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.isdefined</code> as a field
	 */
	public static Field<Boolean> isdefined(Field<Object> __1, Field<String> __2) {
		Isdefined f = new Isdefined();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.isexists</code>
	 */
	public static Boolean isexists(Configuration configuration, Object __1, String __2) {
		Isexists f = new Isexists();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.isexists</code> as a field
	 */
	public static Field<Boolean> isexists(Object __1, String __2) {
		Isexists f = new Isexists();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.isexists</code> as a field
	 */
	public static Field<Boolean> isexists(Field<Object> __1, Field<String> __2) {
		Isexists f = new Isexists();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.populate_record</code>
	 */
	public static Object populateRecord(Configuration configuration, Object __1, Object __2) {
		PopulateRecord f = new PopulateRecord();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.populate_record</code> as a field
	 */
	public static Field<Object> populateRecord(Object __1, Object __2) {
		PopulateRecord f = new PopulateRecord();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.populate_record</code> as a field
	 */
	public static Field<Object> populateRecord(Field<Object> __1, Field<Object> __2) {
		PopulateRecord f = new PopulateRecord();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.slice</code>
	 */
	public static Object slice(Configuration configuration, Object __1, String[] __2) {
		Slice f = new Slice();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.slice</code> as a field
	 */
	public static Field<Object> slice(Object __1, String[] __2) {
		Slice f = new Slice();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.slice</code> as a field
	 */
	public static Field<Object> slice(Field<Object> __1, Field<String[]> __2) {
		Slice f = new Slice();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.slice_array</code>
	 */
	public static String[] sliceArray(Configuration configuration, Object __1, String[] __2) {
		SliceArray f = new SliceArray();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.slice_array</code> as a field
	 */
	public static Field<String[]> sliceArray(Object __1, String[] __2) {
		SliceArray f = new SliceArray();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.slice_array</code> as a field
	 */
	public static Field<String[]> sliceArray(Field<Object> __1, Field<String[]> __2) {
		SliceArray f = new SliceArray();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Call <code>public.tconvert</code>
	 */
	public static Object tconvert(Configuration configuration, String __1, String __2) {
		Tconvert f = new Tconvert();
		f.set__1(__1);
		f.set__2(__2);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.tconvert</code> as a field
	 */
	public static Field<Object> tconvert(String __1, String __2) {
		Tconvert f = new Tconvert();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.tconvert</code> as a field
	 */
	public static Field<Object> tconvert(Field<String> __1, Field<String> __2) {
		Tconvert f = new Tconvert();
		f.set__1(__1);
		f.set__2(__2);

		return f.asField();
	}

	/**
	 * Get <code>public.each</code> as a field
	 */
	public static Each each(Object hs) {
		return Each.EACH.call(hs);
	}

	/**
	 * Get <code>public.each</code> as a field
	 */
	public static Each each(Field<Object> hs) {
		return Each.EACH.call(hs);
	}

	/**
	 * Get <code>public.skeys</code> as a field
	 */
	public static Skeys skeys(Object __1) {
		return Skeys.SKEYS.call(__1);
	}

	/**
	 * Get <code>public.skeys</code> as a field
	 */
	public static Skeys skeys(Field<Object> __1) {
		return Skeys.SKEYS.call(__1);
	}

	/**
	 * Get <code>public.svals</code> as a field
	 */
	public static Svals svals(Object __1) {
		return Svals.SVALS.call(__1);
	}

	/**
	 * Get <code>public.svals</code> as a field
	 */
	public static Svals svals(Field<Object> __1) {
		return Svals.SVALS.call(__1);
	}
}
