/**
 * This class is generated by jOOQ
 */
package com.example.model;


import com.example.model.tables.Note;
import com.example.model.tables.Notetype;
import com.example.model.tables.Site;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.note
	 */
	public static final Note NOTE = com.example.model.tables.Note.NOTE;

	/**
	 * The table public.notetype
	 */
	public static final Notetype NOTETYPE = com.example.model.tables.Notetype.NOTETYPE;

	/**
	 * The table public.site
	 */
	public static final Site SITE = com.example.model.tables.Site.SITE;
}
