/**
 * This class is generated by jOOQ
 */
package com.example.model;


import com.example.model.tables.Note;
import com.example.model.tables.Notetype;
import com.example.model.tables.SchemaVersion;
import com.example.model.tables.Tenant;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.note
	 */
	public static final Note NOTE = com.example.model.tables.Note.NOTE;

	/**
	 * The table public.notetype
	 */
	public static final Notetype NOTETYPE = com.example.model.tables.Notetype.NOTETYPE;

	/**
	 * The table public.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = com.example.model.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table public.tenant
	 */
	public static final Tenant TENANT = com.example.model.tables.Tenant.TENANT;
}
