/**
 * This class is generated by jOOQ
 */
package com.example.model.tables;


import com.example.model.Public;
import com.example.model.tables.records.EachRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Each extends TableImpl<EachRecord> {

	private static final long serialVersionUID = -1252897616;

	/**
	 * The reference instance of <code>public.each</code>
	 */
	public static final Each EACH = new Each();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EachRecord> getRecordType() {
		return EachRecord.class;
	}

	/**
	 * The column <code>public.each.key</code>.
	 */
	public final TableField<EachRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.each.value</code>.
	 */
	public final TableField<EachRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>public.each</code> table reference
	 */
	public Each() {
		this("each", null);
	}

	/**
	 * Create an aliased <code>public.each</code> table reference
	 */
	public Each(String alias) {
		this(alias, EACH);
	}

	private Each(String alias, Table<EachRecord> aliased) {
		this(alias, aliased, new Field[1]);
	}

	private Each(String alias, Table<EachRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Each as(String alias) {
		return new Each(alias, this, parameters);
	}

	/**
	 * Rename this table
	 */
	public Each rename(String name) {
		return new Each(name, null, parameters);
	}

	/**
	 * Call this table-valued function
	 */
	public Each call(Object hs) {
		return new Each(getName(), null, new Field[] { DSL.val(hs) });
	}

	/**
	 * Call this table-valued function
	 */
	public Each call(Field<Object> hs) {
		return new Each(getName(), null, new Field[] { hs });
	}
}
