/**
 * This class is generated by jOOQ
 */
package com.example.model.tables;


import com.example.model.Keys;
import com.example.model.Public;
import com.example.model.tables.records.SiteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Site extends TableImpl<SiteRecord> {

	private static final long serialVersionUID = 314836357;

	/**
	 * The reference instance of <code>public.site</code>
	 */
	public static final Site SITE = new Site();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SiteRecord> getRecordType() {
		return SiteRecord.class;
	}

	/**
	 * The column <code>public.site.id</code>.
	 */
	public final TableField<SiteRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.site.public_key</code>.
	 */
	public final TableField<SiteRecord, String> PUBLIC_KEY = createField("public_key", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.site</code> table reference
	 */
	public Site() {
		this("site", null);
	}

	/**
	 * Create an aliased <code>public.site</code> table reference
	 */
	public Site(String alias) {
		this(alias, SITE);
	}

	private Site(String alias, Table<SiteRecord> aliased) {
		this(alias, aliased, null);
	}

	private Site(String alias, Table<SiteRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SiteRecord> getPrimaryKey() {
		return Keys.SITE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SiteRecord>> getKeys() {
		return Arrays.<UniqueKey<SiteRecord>>asList(Keys.SITE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Site as(String alias) {
		return new Site(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Site rename(String name) {
		return new Site(name, null);
	}
}
