/**
 * This class is generated by jOOQ
 */
package com.example.model.tables;


import com.example.model.Public;
import com.example.model.tables.records.SkeysRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Skeys extends TableImpl<SkeysRecord> {

	private static final long serialVersionUID = 677933329;

	/**
	 * The reference instance of <code>public.skeys</code>
	 */
	public static final Skeys SKEYS = new Skeys();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SkeysRecord> getRecordType() {
		return SkeysRecord.class;
	}

	/**
	 * Create a <code>public.skeys</code> table reference
	 */
	public Skeys() {
		this("skeys", null);
	}

	/**
	 * Create an aliased <code>public.skeys</code> table reference
	 */
	public Skeys(String alias) {
		this(alias, SKEYS);
	}

	private Skeys(String alias, Table<SkeysRecord> aliased) {
		this(alias, aliased, new Field[1]);
	}

	private Skeys(String alias, Table<SkeysRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Skeys as(String alias) {
		return new Skeys(alias, this, parameters);
	}

	/**
	 * Rename this table
	 */
	public Skeys rename(String name) {
		return new Skeys(name, null, parameters);
	}

	/**
	 * Call this table-valued function
	 */
	public Skeys call(Object __1) {
		return new Skeys(getName(), null, new Field[] { DSL.val(__1) });
	}

	/**
	 * Call this table-valued function
	 */
	public Skeys call(Field<Object> __1) {
		return new Skeys(getName(), null, new Field[] { __1 });
	}
}
