/**
 * This class is generated by jOOQ
 */
package com.example.model.tables;


import com.example.model.Public;
import com.example.model.tables.records.SvalsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Svals extends TableImpl<SvalsRecord> {

	private static final long serialVersionUID = -1004920829;

	/**
	 * The reference instance of <code>public.svals</code>
	 */
	public static final Svals SVALS = new Svals();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SvalsRecord> getRecordType() {
		return SvalsRecord.class;
	}

	/**
	 * Create a <code>public.svals</code> table reference
	 */
	public Svals() {
		this("svals", null);
	}

	/**
	 * Create an aliased <code>public.svals</code> table reference
	 */
	public Svals(String alias) {
		this(alias, SVALS);
	}

	private Svals(String alias, Table<SvalsRecord> aliased) {
		this(alias, aliased, new Field[1]);
	}

	private Svals(String alias, Table<SvalsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Svals as(String alias) {
		return new Svals(alias, this, parameters);
	}

	/**
	 * Rename this table
	 */
	public Svals rename(String name) {
		return new Svals(name, null, parameters);
	}

	/**
	 * Call this table-valued function
	 */
	public Svals call(Object __1) {
		return new Svals(getName(), null, new Field[] { DSL.val(__1) });
	}

	/**
	 * Call this table-valued function
	 */
	public Svals call(Field<Object> __1) {
		return new Svals(getName(), null, new Field[] { __1 });
	}
}
