/**
 * This class is generated by jOOQ
 */
package com.example.model.tables;


import com.example.model.Keys;
import com.example.model.Public;
import com.example.model.tables.records.TenantRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tenant extends TableImpl<TenantRecord> {

	private static final long serialVersionUID = 1035158685;

	/**
	 * The reference instance of <code>public.tenant</code>
	 */
	public static final Tenant TENANT = new Tenant();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TenantRecord> getRecordType() {
		return TenantRecord.class;
	}

	/**
	 * The column <code>public.tenant.id</code>.
	 */
	public final TableField<TenantRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.tenant.public_key</code>.
	 */
	public final TableField<TenantRecord, String> PUBLIC_KEY = createField("public_key", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.tenant</code> table reference
	 */
	public Tenant() {
		this("tenant", null);
	}

	/**
	 * Create an aliased <code>public.tenant</code> table reference
	 */
	public Tenant(String alias) {
		this(alias, TENANT);
	}

	private Tenant(String alias, Table<TenantRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tenant(String alias, Table<TenantRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TenantRecord> getPrimaryKey() {
		return Keys.TENANT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TenantRecord>> getKeys() {
		return Arrays.<UniqueKey<TenantRecord>>asList(Keys.TENANT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tenant as(String alias) {
		return new Tenant(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tenant rename(String name) {
		return new Tenant(name, null);
	}
}
