/**
 * This class is generated by jOOQ
 */
package com.example.model.routines;


import com.example.model.Public;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Akeys extends AbstractRoutine<String[]> {

	private static final long serialVersionUID = 1424436895;

	/**
	 * The parameter <code>public.akeys.RETURN_VALUE</code>.
	 */
	public static final Parameter<String[]> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), false);

	/**
	 * The parameter <code>public.akeys._1</code>.
	 */
	public static final Parameter<Object> _1 = createParameter("_1", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), false);

	/**
	 * Create a new routine call instance
	 */
	public Akeys() {
		super("akeys", Public.PUBLIC, org.jooq.impl.SQLDataType.CLOB.getArrayDataType());

		setReturnParameter(RETURN_VALUE);
		addInParameter(_1);
	}

	/**
	 * Set the <code>_1</code> parameter IN value to the routine
	 */
	public void set__1(Object value) {
		setValue(_1, value);
	}

	/**
	 * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__1(Field<Object> field) {
		setField(_1, field);
	}
}
